### ISSUE TITLE
Having error Unknown File Extension while migrating the  migrations

### ISSUE THREAD

**Issue by princevora** [thanathip41/tspace-mysql#1]
Recently i installed the tspace-mysql because it seems to be so easy and clear to code. but whenever i create a migration and migrate it using `npx tspace-mysql migrate --dir...` it shows error that "unkown file extension" i dont know what is the problem  if anyone has seen this problem help me solve it. the image is below...

![image](https://github.com/thanathip41/tspace-mysql/assets/122656064/92fe382e-96d5-4241-bf12-36e2a2e660bb)

**Comment by thanathip41** [comment]
Could you re-write file create_users_table.ts to .js  , then try use npx  tspace-mysql migrate --dir --type=js,
Your project base on type .js 

If there are any issues, i will fix it next version ,thank you

* i recommend you use https://www.npmjs.com/package/tspace-mysql#sync

**Comment by princevora** [comment]
I got the temporary solution, in your package.json you can temprory  change the ` "type": "module"  to  "type": "commonjs" `, but it is temporary solution not a permanent solution, i hope that in upcoming version or commit that will be solved,
