### ISSUE TITLE
Having issue while using migrate command

### ISSUE THREAD

**Issue by princevora** [thanathip41/tspace-mysql#3]
I was making a new migration called `chats` table 

this was my command `npx tspace-mysql make:migration chats --dir=DB/migrations`

When it creates a by default migration like 
![image](https://github.com/thanathip41/tspace-mysql/assets/122656064/89703a9c-2fa8-49da-8fae-8b5852d6c034)

i didnt even touched it and when i runs it, it shows me error in console that Invalid default value for 'updated_at'

![image](https://github.com/thanathip41/tspace-mysql/assets/122656064/b342f885-c15b-4e39-94df-812f128a349c)

i need to edit the migrations from 
`created_at : new Blueprint().null().timestamp(),
 updated_at : new Blueprint().null().timestamp(),`

to 

`created_at: new Blueprint().timestamp().null(),
updated_at: new Blueprint().timestamp().null(),`

Correct me if thats any problem from myside

as earlier this is a temprory solution i am hoping to solve it in upcoming versions 

Thank you

**Comment by thanathip41** [comment]
Thanks, I'm ready to fix all of your concerns it in version 1.6.6-dev.1. --tag dev.
I hope you can try again.

If there aren't any issues, I will release a new version.

Thank you
