### ISSUE TITLE
Too Many Connections 

### ISSUE THREAD

**Issue by princevora** [thanathip41/tspace-mysql#5]
I am having too many connections error and i dont see  any option to disable to ( disconnect ) the connection.

![image](https://github.com/thanathip41/tspace-mysql/assets/122656064/25fc0872-5117-41a6-ae6a-f2f18d544555)

**Comment by thanathip41** [comment]
Could you please provide information about your new connection in your code, some  .getConnection() etc ?

 and the maximum number of connections allowed on your database server?
 
 Thank your.

**Comment by princevora** [comment]
![image](https://github.com/thanathip41/tspace-mysql/assets/122656064/2ff96d67-9762-413b-9971-5503f3f427ca)

its 151

**Comment by thanathip41** [comment]
Thanks for the information, but I'm not sure what's happening. 
I'm testing benchmarks with multiple connections ( max_connection same you "151" connections ) 
but haven't encountered any "Too many connections" errors.

Could you please check if the connection is being established in a loop or another incorrect pattern? 
This might be causing the issue.

// some method connection
.bind(connection) or .getConnection()

 The information. It is important to me in finding and resolving the issues.
 
 Thank you. your time

**Comment by princevora** [comment]
I will let you know if i get any error using these methods
